function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "adc_software_trigger_s32k14x"};
	this.sidHashMap["adc_software_trigger_s32k14x"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "adc_software_trigger_s32k14x:12"};
	this.sidHashMap["adc_software_trigger_s32k14x:12"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "adc_software_trigger_s32k14x:34"};
	this.sidHashMap["adc_software_trigger_s32k14x:34"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/ADC_Config"] = {sid: "adc_software_trigger_s32k14x:2"};
	this.sidHashMap["adc_software_trigger_s32k14x:2"] = {rtwname: "<Root>/ADC_Config"};
	this.rtwnameHashMap["<Root>/ADC_Start"] = {sid: "adc_software_trigger_s32k14x:4"};
	this.sidHashMap["adc_software_trigger_s32k14x:4"] = {rtwname: "<Root>/ADC_Start"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "adc_software_trigger_s32k14x:12"};
	this.sidHashMap["adc_software_trigger_s32k14x:12"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<Root>/Data Store Memory"] = {sid: "adc_software_trigger_s32k14x:37"};
	this.sidHashMap["adc_software_trigger_s32k14x:37"] = {rtwname: "<Root>/Data Store Memory"};
	this.rtwnameHashMap["<Root>/Data Store Write"] = {sid: "adc_software_trigger_s32k14x:38"};
	this.sidHashMap["adc_software_trigger_s32k14x:38"] = {rtwname: "<Root>/Data Store Write"};
	this.rtwnameHashMap["<Root>/Data Type Conversion"] = {sid: "adc_software_trigger_s32k14x:41"};
	this.sidHashMap["adc_software_trigger_s32k14x:41"] = {rtwname: "<Root>/Data Type Conversion"};
	this.rtwnameHashMap["<Root>/Digital_Output"] = {sid: "adc_software_trigger_s32k14x:13"};
	this.sidHashMap["adc_software_trigger_s32k14x:13"] = {rtwname: "<Root>/Digital_Output"};
	this.rtwnameHashMap["<Root>/Digital_Output1"] = {sid: "adc_software_trigger_s32k14x:40"};
	this.sidHashMap["adc_software_trigger_s32k14x:40"] = {rtwname: "<Root>/Digital_Output1"};
	this.rtwnameHashMap["<Root>/FreeMaster_Config"] = {sid: "adc_software_trigger_s32k14x:35"};
	this.sidHashMap["adc_software_trigger_s32k14x:35"] = {rtwname: "<Root>/FreeMaster_Config"};
	this.rtwnameHashMap["<Root>/MBD_S32K14x_Config_Information"] = {sid: "adc_software_trigger_s32k14x:1"};
	this.sidHashMap["adc_software_trigger_s32k14x:1"] = {rtwname: "<Root>/MBD_S32K14x_Config_Information"};
	this.rtwnameHashMap["<Root>/Model Info"] = {sid: "adc_software_trigger_s32k14x:34"};
	this.sidHashMap["adc_software_trigger_s32k14x:34"] = {rtwname: "<Root>/Model Info"};
	this.rtwnameHashMap["<S1>:3"] = {sid: "adc_software_trigger_s32k14x:12:3"};
	this.sidHashMap["adc_software_trigger_s32k14x:12:3"] = {rtwname: "<S1>:3"};
	this.rtwnameHashMap["<S1>:6"] = {sid: "adc_software_trigger_s32k14x:12:6"};
	this.sidHashMap["adc_software_trigger_s32k14x:12:6"] = {rtwname: "<S1>:6"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "adc_software_trigger_s32k14x:12:1"};
	this.sidHashMap["adc_software_trigger_s32k14x:12:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:7"] = {sid: "adc_software_trigger_s32k14x:12:7"};
	this.sidHashMap["adc_software_trigger_s32k14x:12:7"] = {rtwname: "<S1>:7"};
	this.rtwnameHashMap["<S2>/EmptySubsystem"] = {sid: "adc_software_trigger_s32k14x:34:1"};
	this.sidHashMap["adc_software_trigger_s32k14x:34:1"] = {rtwname: "<S2>/EmptySubsystem"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
