set MATLAB=C:\Program Files\MATLAB\R2018b
"%MATLAB%\bin\win64\gmake" -f lpuart_hello_world_s32k14x.mk COPY_MDLREF_INCLUDES=0 GENERATE_ERT_S_FUNCTION=0 INCLUDE_MDL_TERMINATE_FCN=1 COMBINE_OUTPUT_UPDATE_FCNS=1 MULTI_INSTANCE_CODE=0 INTEGER_CODE=0 ISPROTECTINGMODEL=NOTPROTECTING
